sisters = ['becca', 'ashley', 'kelsey', 'maggie', 'grace']
print(sisters)
print(sisters[0].title())
print(sisters[1].title())
print(sisters[-1].title())
message = "My baby sister's name is " + sisters[-1].title() + "."
print(message)
sisters[0] = 'rebecca'
print(sisters)
sisters.append('ruth')
print(sisters)
sisters.insert(3, 'margaret')
print(sisters)
del sisters[6]
print(sisters)
popped_sister = sisters.pop()
print(sisters)
print(popped_sister)
print("My friend " + popped_sister.title() + " is like a sister to me.")
sisters.remove('margaret')
print(sisters)
print(sorted(sisters))
print(sisters)
sisters.reverse()
print(sisters)
sisters.reverse()
print(sisters)
sisters.sort()
print(sisters)
sisters.sort(reverse=True)
print(sisters)
print(len(sisters))